name: Test

on:
  - push
  - pull_request

jobs:
  matrix-test:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          # - windows-latest
        python:
          - 3.7
          - 3.8
        ipfs:
          - 0.4
          - 0.5
          - 0.6
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} Py-${{ matrix.python }} IPFS-${{ matrix.ipfs }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Set up IPFS ${{ matrix.ipfs }}
        uses: ibnesayeed/setup-ipfs@master
        with:
          ipfs_version: ${{ matrix.ipfs }}
          run_daemon: true
      - name: Install Python Dependencies
        shell: bash
        run: |
          pip install -r requirements.txt
          pip install -r test-requirements.txt
      - name: Run Tests
        shell: bash
        run: py.test -s --cov=./
