name: Test

on:
  - push
  - pull_request

jobs:
  matrix-test:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          # - windows-latest
        python:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
        ipfs:
          - "0.28"
          - "0.29"
          - "0.30"
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} Py-${{ matrix.python }} IPFS-${{ matrix.ipfs }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Set up IPFS ${{ matrix.ipfs }}
        uses: oduwsdl/setup-ipfs@main
        with:
          ipfs_version: ${{ matrix.ipfs }}
          run_daemon: true
      - name: Install Python Dependencies
        shell: bash
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r test-requirements.txt
      - name: Run Tests
        shell: bash
        run: py.test -s --cov=./
